apiVersion: v1
kind: Namespace
metadata:
  name: nginx-proxy

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        image: piyush8085/nginx-proxy-9:ica
        ports:
        - containerPort: 80
