apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-proxy
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30070  # Choose a port in the range 30000-32767
  selector:
    app: nginx-proxy
