apiVersion: v1
kind: Namespace
metadata:
  name: mariadb

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: piyush8085/db:ica
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: somewordpress
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
        ports:
        - containerPort: 3306

    ##Adding the Application Code
