apiVersion: v1
kind: Namespace
metadata:
  name: wp-app

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-app
  namespace: wp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp-app
  template:
    metadata:
      labels:
        app: wp-app
    spec:
      containers:
      - name: wp
        image: riya/wp-2:ica
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wp-config
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wp-secrets
              key: WORDPRESS_DB_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-secrets
              key: WORDPRESS_DB_PASSWORD
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wp-config
              key: WORDPRESS_DB_NAME
        ports:
        - containerPort: 80
